# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vws_W-fDk4xyDTD0V8bfCVZSJ7EQ-AaZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/stocks.csv")

df.head()

df.info()

df['Date'] = pd.to_datetime(df['Date'])

df.describe()

df.isnull().sum()

df.plot(x='Date', y='Close', title='Stock Closing Price Over Time', figsize=(10, 5))

df.head(2)



import matplotlib.pyplot as plt

df['price range'] = df['High'] - df['Low']

plt.figure(figsize=(10, 5))

plt.bar(df['Date'], df['price range'])

plt.title('Stock Market Range Over Time')
plt.xlabel('Date')
plt.ylabel('Price Range')


plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

df.info()

df.plot(x='Date', y='Volume', kind='line', title='Daily Trading Volume', figsize=(12, 4))

df['MA7'] = df['Close'].rolling(window=7).mean()
df['MA14'] = df['Close'].rolling(window=14).mean()
df.plot(x='Date', y=['Close', 'MA7', 'MA14'], title='Moving Averages', figsize=(10, 5))

df.info()

total_volumeby_Ticker = df.groupby('Ticker')['Volume']
total_volumeby_Ticker.plot(kind='bar',figsize=(12,5),color='blue',title='total_volumeby_Ticker')
plt.xlabel("Ticker")
plt.ylabel("total volume")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['Close'], kde=True, color='orange')
plt.title('Distribution of Closing Prices')
plt.xlabel('Closing Price')
plt.ylabel('Density')
plt.grid(True)
plt.show()

